# Sample Prometheus configuration for scraping jhipster applications

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http' enable https in case your application is server via https
    #scheme: https
    # basic auth is not needed by default. See https://www.jhipster.tech/monitoring/#configuring-metrics-forwarding for details
    #basic_auth:
    # username: admin
    # password: admin
    metrics_path: /management/prometheus
    static_configs:
      - targets:
          # On MacOS, replace localhost by host.docker.internal
          - localhost:8080
